
// This is an autogenerated file, edit at your own peril.
#ifndef IMAGES_H
#define IMAGES_H
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

// This is a compressed version to save space. 
// Store length of consecuatly same pixel value.
// When rendering we render that many pixels of that color.
struct vlu_seg {
  uint16_t len; // How many consecuetive pixels of ths same color.
  uint8_t vlu;  // What pixel value to render.
};
 
/// An image is a collection of vlu_seg segments.
struct vlu_img {
  const struct vlu_seg* segs; // The segments this image contains
  uint16_t n_segs;      // Number of segments in this image.
};

///Function pointer to a function that send 1 byte to screen
typedef void (*images_send_data)(uint8_t byt);

/// The actual decompress and render function
int images_render(
    const struct vlu_img* img,
    const images_send_data send_fn,
    const uint32_t max_pixels);

// image: image_M.png, size: 2010
extern const struct vlu_img image_M;

// image: image_Z.png, size: 4800
extern const struct vlu_img image_Z;

// image: image_L.png, size: 1725
extern const struct vlu_img image_L;

// image: image_N.png, size: 1908
extern const struct vlu_img image_N;

// image: image_Y.png, size: 2331
extern const struct vlu_img image_Y;

// image: image_X.png, size: 4383
extern const struct vlu_img image_X;

// image: image_O.png, size: 3561
extern const struct vlu_img image_O;

// image: image_K.png, size: 3441
extern const struct vlu_img image_K;

// image: image_J.png, size: 1596
extern const struct vlu_img image_J;

// image: image_H.png, size: 1812
extern const struct vlu_img image_H;

// image: image_I.png, size: 2493
extern const struct vlu_img image_I;

// image: image_S.png, size: 4437
extern const struct vlu_img image_S;

// image: image_D.png, size: 3213
extern const struct vlu_img image_D;

// image: image_E.png, size: 4125
extern const struct vlu_img image_E;

// image: image_R.png, size: 3975
extern const struct vlu_img image_R;

// image: image_P.png, size: 2847
extern const struct vlu_img image_P;

// image: image_G.png, size: 4344
extern const struct vlu_img image_G;

// image: image_F.png, size: 2859
extern const struct vlu_img image_F;

// image: image_Q.png, size: 4227
extern const struct vlu_img image_Q;

// image: image_B.png, size: 4809
extern const struct vlu_img image_B;

// image: image_U.png, size: 1812
extern const struct vlu_img image_U;

// image: image_T.png, size: 2313
extern const struct vlu_img image_T;

// image: image_C.png, size: 3774
extern const struct vlu_img image_C;

// image: image_A.png, size: 3321
extern const struct vlu_img image_A;

// image: image_V.png, size: 2493
extern const struct vlu_img image_V;

// image: image_W.png, size: 2553
extern const struct vlu_img image_W;

// image: nj_racing.png, size: 12261
extern const struct vlu_img nj_racing;


#ifdef __cplusplus
} // extern "C"
#endif

#endif // IMAGES_H
